TFG/TFG/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views

from app.views import Login, AdminLogin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^principal/', include('app.urls', namespace='principal')),
    url(r'^$', Login.as_view(), name='login'),
    url(r'^paneladmin/$', AdminLogin.as_view(), name='admin-login'),
    url(r'^logout/$', auth_views.logout,{'next_page': '/'}, name='logout'),
    url(r'^logout_admin/$', auth_views.logout,{'next_page': '/paneladmin'}, name='logout-admin'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

TFG/app/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views

from app.views import detail_app_view, AppListView, create_user_view, \
    create_user_view, change_password, UserUpdate, contact_view, AppFormView, create_task_view, tasks_app_view, \
    admin_view, UserAdminListView, AppAdminListView, MyCompanyAdminListView, TaskAdminListView, \
    ImageSlideShowAdminListView, ParamInputAdminListView, SectionAdminListView, NewImageSlideShowAdminListView, \
    DeleteImageSlideShowAdminListView, DeleteUserAdminListView, NewUserAdminListView, EditUserAdminListView, \
    NewAppAdminListView, DeleteAppAdminListView, EditAppAdminListView, EditMyCompanyAdminListView, \
    NewSectionAdminListView, DeleteSectionAdminListView, EditSectionAdminListView, EditTaskAdminListView, \
    DeleteTaskAdminListView, NewTaskAdminListView, \
    ParamInputFileAdminListView, NewParamInputFileAdminListView, EditParamInputFileAdminListView, \
    DeleteParamInputFileAdminListView, ParamInputTextAdminListView, NewParamInputTextAdminListView, \
    DeleteParamInputTextAdminListView, EditParamInputTextAdminListView, ParamInputOptionAdminListView, \
    NewParamInputOptionAdminListView, DeleteParamInputOptionAdminListView, EditParamInputOptionAdminListView, \
    ParamInputSelectAdminListView, NewParamInputSelectAdminListView, DeleteParamInputSelectAdminListView, \
    EditParamInputSelectAdminListView, TaskDetailView, SendAppCompatibilityView, getting_started_view, citations_view, \
    forget_password, send_password, download_task_view, check_state_task_view

urlpatterns = [
    #Registro
    url(r'^create_user/$',create_user_view, name = 'create-user-view'),

    #Ventana detalles aplicacion
    url(r'^detail/(?P<pk>\d+)$', detail_app_view, name='detail-apps-view'),

    #Ventana tabla con las tareas de la aplicacion
    url(r'^tasks/(?P<pk>\d+)$', tasks_app_view, name='tasks-apps-view'),

    #Formulario creacion tarea
    url(r'^app/form/(?P<pk>\d+)$', login_required(AppFormView.as_view()), name='form-apps-view'),

    #Vista detalles de tarea individual
    url(r'^task/detail/(?P<pk>\d+)$', login_required(TaskDetailView.as_view()), name='task-detail-view'),

    #Enviar parametros a aplicacion compatible
    url(r'^send_app_compatibility/(?P<pk>\d+)$', login_required(SendAppCompatibilityView.as_view()), name='send-app-compatibility-view'),

    #Menu principal del dashboard
    url(r'^dashboard/$', login_required(AppListView.as_view()), name='list-apps-view'),

    #Editar usuario
    url(r'^user/edit/(?P<pk>\d+)$', login_required(UserUpdate.as_view()), name='edit-user-view'),

    #Cambiar password
    url(r'^password/$', change_password, name='change_password'),

    #Olvido password
    url(r'^forget_password/$', forget_password, name='forget-password-view'),
    url(r'^send_password/$', send_password, name='send-password-view'),

    #Menu Index
    url(r'^contact/$', contact_view, name='contact-view'),
    url(r'^getting_started/$', getting_started_view, name='getting-started-view'),
    url(r'^citations/$', citations_view, name='citations-view'),

    # Crear Tarea
    url(r'^create_task/(?P<pk>\d+)$',login_required(create_task_view), name = 'create-task-view'),

    # Descargar Tarea
    url(r'^download_task/(?P<pk>\d+)$',login_required(download_task_view), name = 'download-task-view'),

    # Ver Estado Tarea
    url(r'^check_state_task/(?P<pk>\d+)$',login_required(check_state_task_view), name = 'check-state-task-view'),

    # Dashboard admin
    url(r'^admin_view/$', login_required(admin_view), name='admin-view'),


    # Admin User
    url(r'^user_admin_view/$', login_required(UserAdminListView.as_view()), name='list-user-admin-view'),
    url(r'^new_user_admin_view/$', login_required(NewUserAdminListView.as_view()), name='new-user-admin-view'),
    url(r'^delete_user_admin_view/(?P<pk>\d+)$', login_required(DeleteUserAdminListView.as_view()), name='delete-user-admin-view'),
    url(r'^edit_user_admin_view/(?P<pk>\d+)$', login_required(EditUserAdminListView.as_view()), name='edit-user-admin-view'),

    # Admin App
    url(r'^app_admin_view/$', login_required(AppAdminListView.as_view()), name='list-app-admin-view'),
    url(r'^new_app_admin_view/$', login_required(NewAppAdminListView.as_view()), name='new-app-admin-view'),
    url(r'^delete_app_admin_view/(?P<pk>\d+)$', login_required(DeleteAppAdminListView.as_view()), name='delete-app-admin-view'),
    url(r'^edit_app_admin_view/(?P<pk>\d+)$', login_required(EditAppAdminListView.as_view()), name='edit-app-admin-view'),

    # Admin MyCompany
    url(r'^mycompany_admin_view/$', login_required(MyCompanyAdminListView.as_view()), name='list-mycompany-admin-view'),
    url(r'^edit_mycompany_admin_view/(?P<pk>\d+)$', login_required(EditMyCompanyAdminListView.as_view()), name='edit-mycompany-admin-view'),

    # Admin Task
    url(r'^task_admin_view/$', login_required(TaskAdminListView.as_view()), name='list-task-admin-view'),
    url(r'^new_task_admin_view/$', login_required(NewTaskAdminListView.as_view()), name='new-task-admin-view'),
    url(r'^delete_task_admin_view/(?P<pk>\d+)$', login_required(DeleteTaskAdminListView.as_view()), name='delete-task-admin-view'),
    url(r'^edit_task_admin_view/(?P<pk>\d+)$', login_required(EditTaskAdminListView.as_view()), name='edit-task-admin-view'),

    # Admin ImageSlideShow
    url(r'^image_admin_view/$', login_required(ImageSlideShowAdminListView.as_view()), name='list-image-admin-view'),
    url(r'^new_image_admin_view/$', login_required(NewImageSlideShowAdminListView.as_view()), name='new-image-admin-view'),
    url(r'^delete_image_admin_view/(?P<pk>\d+)$', login_required(DeleteImageSlideShowAdminListView.as_view()), name='delete-image-admin-view'),

    # Admin Param Input
    url(r'^param_admin_view/$', login_required(ParamInputAdminListView.as_view()), name='list-param-admin-view'),
    url(r'^param_file_admin_view/$', login_required(ParamInputFileAdminListView.as_view()), name='list-param-file-admin-view'),
    url(r'^new_param_file_admin_view/$', login_required(NewParamInputFileAdminListView.as_view()), name='new-param-file-admin-view'),
    url(r'^delete_param_file_admin_view/(?P<pk>\d+)$', login_required(DeleteParamInputFileAdminListView.as_view()), name='delete-param-file-admin-view'),
    url(r'^edit_param_file_admin_view/(?P<pk>\d+)$', login_required(EditParamInputFileAdminListView.as_view()), name='edit-param-file-admin-view'),

    url(r'^param_text_admin_view/$', login_required(ParamInputTextAdminListView.as_view()), name='list-param-text-admin-view'),
    url(r'^new_param_text_admin_view/$', login_required(NewParamInputTextAdminListView.as_view()), name='new-param-text-admin-view'),
    url(r'^delete_param_text_admin_view/(?P<pk>\d+)$', login_required(DeleteParamInputTextAdminListView.as_view()), name='delete-param-text-admin-view'),
    url(r'^edit_param_text_admin_view/(?P<pk>\d+)$', login_required(EditParamInputTextAdminListView.as_view()), name='edit-param-text-admin-view'),

    url(r'^param_option_admin_view/$', login_required(ParamInputOptionAdminListView.as_view()), name='list-param-option-admin-view'),
    url(r'^new_param_option_admin_view/$', login_required(NewParamInputOptionAdminListView.as_view()), name='new-param-option-admin-view'),
    url(r'^delete_param_option_admin_view/(?P<pk>\d+)$', login_required(DeleteParamInputOptionAdminListView.as_view()), name='delete-param-option-admin-view'),
    url(r'^edit_param_option_admin_view/(?P<pk>\d+)$', login_required(EditParamInputOptionAdminListView.as_view()), name='edit-param-option-admin-view'),

    url(r'^param_select_admin_view/$', login_required(ParamInputSelectAdminListView.as_view()), name='list-param-select-admin-view'),
    url(r'^new_param_select_admin_view/$', login_required(NewParamInputSelectAdminListView.as_view()), name='new-param-select-admin-view'),
    url(r'^delete_param_select_admin_view/(?P<pk>\d+)$', login_required(DeleteParamInputSelectAdminListView.as_view()), name='delete-param-select-admin-view'),
    url(r'^edit_param_select_admin_view/(?P<pk>\d+)$', login_required(EditParamInputSelectAdminListView.as_view()), name='edit-param-select-admin-view'),

    # Admin Section
    url(r'^section_admin_view/$', login_required(SectionAdminListView.as_view()), name='list-section-admin-view'),
    url(r'^new_section_admin_view/$', login_required(NewSectionAdminListView.as_view()), name='new-section-admin-view'),
    url(r'^delete_section_admin_view/(?P<pk>\d+)$', login_required(DeleteSectionAdminListView.as_view()), name='delete-section-admin-view'),
    url(r'^edit_section_admin_view/(?P<pk>\d+)$', login_required(EditSectionAdminListView.as_view()), name='edit-section-admin-view'),
]

TFG/templates/new_section_table_admin.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="utf-8">
    <title>GGAFE Panel Admin</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/jpg" href="{% static 'img/cabd.jpg' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}"/>

    <!-- Custom fonts for this template-->
    <link href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">

    <link href="{% static 'css/admin/main.css' %}" rel="stylesheet">
    <link href="{% static 'css/admin/font-style.css' %}" rel="stylesheet">
    <link href="{% static 'css/admin/flexslider.css' %}" rel="stylesheet">
    <link href="{% static 'css/admin/table.css' %}" rel="stylesheet">
    <link href="{% static 'css/admin/register.css' %}" rel="stylesheet">
        <!-- Footer -->
    <link href="{% static 'css/footer-distributed-with-address-and-phones.css' %}" rel="stylesheet">

    <script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>


    <!-- NOTY JAVASCRIPT -->
    <script type="text/javascript" src="{% static 'js/admin/noty/jquery.noty.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/admin/noty/layouts/top.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/admin/noty/layouts/topLeft.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/admin/noty/layouts/topRight.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/admin/noty/layouts/topCenter.js' %}"></script>

    <script src="{% static 'vendor/datatables/jquery.dataTables.js' %}"></script>
    <script src="{% static 'vendor/datatables/dataTables.bootstrap4.js' %}"></script>

    <!-- <script type="text/javascript" src="assets/js/dash-noty.js"></script> This is a Noty bubble when you init the theme-->
    <script type="text/javascript" src="http://code.highcharts.com/highcharts.js"></script>
    <script src="{% static 'js/admin/jquery.flexslider.js' %}" type="text/javascript"></script>

    <script type="text/javascript" src="{% static 'js/admin/admin.js' %}"></script>

    <style type="text/css">
      body {
        padding-top: 60px;
      }

    </style>

    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->


    <!-- Google Fonts call. Font Used Open Sans & Raleway -->
    <link href="http://fonts.googleapis.com/css?family=Raleway:400,300" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet" type="text/css">

    <script type="text/javascript">
    $(document).ready(function () {

        $("#btn-blog-next").click(function () {
            $('#blogCarousel').carousel('next')
        });
        $("#btn-blog-prev").click(function () {
            $('#blogCarousel').carousel('prev')
        });

        $("#btn-client-next").click(function () {
            $('#clientCarousel').carousel('next')
        });
        $("#btn-client-prev").click(function () {
            $('#clientCarousel').carousel('prev')
        });

    });

    $(window).load(function () {

        $('.flexslider').flexslider({
            animation: "slide",
            slideshow: true,
            start: function (slider) {
                $('body').removeClass('loading');
            }
        });
    });


    </script>

    <script type="text/javascript" src="{% static 'js/admin/datatables/jquery.dataTables.js' %}"></script>
  			<script type="text/javascript" charset="utf-8">
  			    $(document).ready(function () {
  			        $('#dt1').dataTable();
  			    });
	</script>
</head>
<body>

<!-- NAVIGATION MENU -->

<!-- NAVIGATION MENU -->

<div class="navbar-nav navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'principal:admin-view' %}"><img src="images/logo30.png" alt=""> GGAFE Panel Admin</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'principal:admin-view' %}"><i class="icon-home icon-white"></i> Home</a></li>
                <li><a href="{% url 'principal:list-user-admin-view' %}"><i class="icon-th icon-white"></i> User</a></li>
                <li><a href="{% url 'principal:list-app-admin-view' %}"><i class="icon-lock icon-white"></i> App</a></li>
                <li><a href="{% url 'principal:list-mycompany-admin-view' %}"><i class="icon-user icon-white"></i> General Information</a></li>
                <li><a href="{% url 'principal:list-task-admin-view' %}"><i class="icon-user icon-white"></i> Task</a></li>
                <li><a href="{% url 'principal:list-image-admin-view' %}"><i class="icon-user icon-white"></i> Image Slide Show</a></li>
                <li><a href="{% url 'principal:list-param-admin-view' %}"><i class="icon-user icon-white"></i> Param Input</a></li>
                <li class="active"><a href="{% url 'principal:list-section-admin-view' %}"><i class="icon-user icon-white"></i> Section</a></li>
                <li><a href="{% url 'logout-admin' %}"><i class="fa fa-sign-out"></i> Log Out</a></li>
            </ul>
        </div><!--/.nav-collapse -->
    </div>
</div>

<div class="container">
    <br />
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12  table-info">
            <div class="col-lg-2"></div>
            <div class="col-lg-8">
                {% if new_section %}
                <form action="{% url 'principal:new-section-admin-view' %}" method="post" enctype="multipart/form-data">
                    <div class="text-center">
                        <h2 id="h2-register">New Section</h2>
                    </div>
                    <div class="form-group">
                        <div class="row">
                            <div class="col-12">
                                {{ sectionform.title.errors }}
                                <label>Title: </label>
                                {{ sectionform.title }}
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-12">
                                {{ sectionform.description.errors }}
                                <label>Description: </label>
                                {{ sectionform.description }}
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-12">
                                {{ sectionform.app.errors }}
                                <label>App: </label>
                                {{ sectionform.app }}
                            </div>
                        </div>
                        <div class="row">
                            {% csrf_token %}
                            <br/>
                            <input class="btn btn-primary btn-block" type="submit" value="Save Changes">
                        </div>
                    </div>
                </form>
                {% else %}
                <form action="{% url 'principal:edit-section-admin-view' id %}" method="post" enctype="multipart/form-data">
                    <div class="text-center">
                        <h2>Edit Section</h2>
                    </div>
                    <div class="form-group">
                        <div class="row">
                            <div class="col-12">
                                {{ sectionform.title.errors }}
                                <label>Title: </label>
                                {{ sectionform.title }}
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-12">
                                {{ sectionform.description.errors }}
                                <label>Description: </label>
                                {{ sectionform.description }}
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-12">
                                {{ sectionform.app.errors }}
                                <label>App: </label>
                                {{ sectionform.app }}
                            </div>
                        </div>
                        <div class="row">
                            {% csrf_token %}
                            <br/>
                            <input class="btn btn-primary btn-block" type="submit" value="Save Changes">
                        </div>
                    </div>
                </form>
                {% endif %}
            </div>
            <div class="col-lg-2"></div>
        </div>
    </div><!-- /row -->
    <br /><br />
</div> <!-- /container -->
<div class="footer-distributed">
    <div class="footer-left">

        <h3>Gene & Genome <span>Annotation For Everybody</span></h3>

        <p class="footer-links">
            <a href="#">Citations</a>
            ·
            <a href="#">Help</a>
            ·
            <a href="#">About</a>
            ·
            <a href="#">Contact</a>
        </p>

        <p class="footer-company-name">CABD &copy; 2018</p>
    </div>

    <div class="footer-center">

        <div>
            <i class="fa fa-map-marker"></i>
            <span style="color:white;">{{ company_name.address }}, Seville, Spain</span>
        </div>

        <div>
            <i class="fa fa-phone"></i>
            <p>{{ company_name.phone }}</p>
        </div>

        <div>
            <i class="fa fa-envelope"></i>
            <p>{{ company_name.email }}</p>
        </div>

    </div>

    <div class="footer-right">

        <p class="footer-company-about">
            <span>About the company</span>
            {{ company_name.description }}
        </p>

        <div class="footer-icons">

            <a href="#"><i class="fa fa-facebook"></i></a>
            <a href="#"><i class="fa fa-twitter"></i></a>
            <a href="#"><i class="fa fa-linkedin"></i></a>
            <a href="#"><i class="fa fa-github"></i></a>

        </div>

    </div>

</div>

</body>
</html>

TFG/templates/param_table_admin.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="utf-8">
    <title>GGAFE Panel Admin</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/jpg" href="{% static 'img/cabd.jpg' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}"/>

    <!-- Custom fonts for this template-->
    <link href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">

    <link href="{% static 'css/admin/main.css' %}" rel="stylesheet">
    <link href="{% static 'css/admin/font-style.css' %}" rel="stylesheet">
    <link href="{% static 'css/admin/flexslider.css' %}" rel="stylesheet">
        <!-- Footer -->
    <link href="{% static 'css/footer-distributed-with-address-and-phones.css' %}" rel="stylesheet">

    <script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>


    <!-- NOTY JAVASCRIPT -->
    <script type="text/javascript" src="{% static 'js/admin/noty/jquery.noty.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/admin/noty/layouts/top.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/admin/noty/layouts/topLeft.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/admin/noty/layouts/topRight.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/admin/noty/layouts/topCenter.js' %}"></script>

    <!-- <script type="text/javascript" src="assets/js/dash-noty.js"></script> This is a Noty bubble when you init the theme-->
    <script type="text/javascript" src="http://code.highcharts.com/highcharts.js"></script>
    <script src="{% static 'js/admin/jquery.flexslider.js' %}" type="text/javascript"></script>

    <script type="text/javascript" src="{% static 'js/admin/admin.js' %}"></script>

    <style type="text/css">
      body {
        padding-top: 60px;
      }

    </style>

    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->


    <!-- Google Fonts call. Font Used Open Sans & Raleway -->
    <link href="http://fonts.googleapis.com/css?family=Raleway:400,300" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet" type="text/css">

    <script type="text/javascript">
    $(document).ready(function () {

        $("#btn-blog-next").click(function () {
            $('#blogCarousel').carousel('next')
        });
        $("#btn-blog-prev").click(function () {
            $('#blogCarousel').carousel('prev')
        });

        $("#btn-client-next").click(function () {
            $('#clientCarousel').carousel('next')
        });
        $("#btn-client-prev").click(function () {
            $('#clientCarousel').carousel('prev')
        });

    });

    $(window).load(function () {

        $('.flexslider').flexslider({
            animation: "slide",
            slideshow: true,
            start: function (slider) {
                $('body').removeClass('loading');
            }
        });
    });


    </script>
</head>
<body>

<!-- NAVIGATION MENU -->

<!-- NAVIGATION MENU -->

<div class="navbar-nav navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'principal:admin-view' %}"><img src="images/logo30.png" alt=""> GGAFE Panel Admin</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'principal:admin-view' %}"><i class="icon-home icon-white"></i> Home</a></li>
                <li><a href="{% url 'principal:list-user-admin-view' %}"><i class="icon-th icon-white"></i> User</a></li>
                <li><a href="{% url 'principal:list-app-admin-view' %}"><i class="icon-lock icon-white"></i> App</a></li>
                <li><a href="{% url 'principal:list-mycompany-admin-view' %}"><i class="icon-user icon-white"></i> General Information</a></li>
                <li><a href="{% url 'principal:list-task-admin-view' %}"><i class="icon-user icon-white"></i> Task</a></li>
                <li><a href="{% url 'principal:list-image-admin-view' %}"><i class="icon-user icon-white"></i> Image Slide Show</a></li>
                <li class="active"><a href="{% url 'principal:list-param-admin-view' %}"><i class="icon-user icon-white"></i> Params Input</a></li>
                <li><a href="{% url 'principal:list-section-admin-view' %}"><i class="icon-user icon-white"></i> Section</a></li>
                <li><a href="{% url 'logout-admin' %}"><i class="fa fa-sign-out"></i> Log Out</a></li>
            </ul>
        </div><!--/.nav-collapse -->
    </div>
</div>

<div class="container">

    <!-- FIRST ROW OF BLOCKS -->
    <div class="row">

        <!-- USER PROFILE BLOCK -->
        <div class="col-sm-3 col-lg-3">
            <a href="{% url 'principal:list-param-file-admin-view' %}">
                <div class="dash-unit">
                    <h1>PARAM INPUT FILE</h1>
                    <br>
                    <div class="info-user">
                        <span aria-hidden="true" class="li_params fs1"></span>
                    </div>
                    <h2>{{ param_file_count }}</h2>
                </div>
            </a>
        </div>

        <!-- DONUT CHART BLOCK -->
        <div class="col-sm-3 col-lg-3">
            <a href="{% url 'principal:list-param-text-admin-view' %}">
                <div class="dash-unit">
                    <h1>PARAM INPUT TEXT</h1>
                    <br>
                    <div class="info-user">
                        <span aria-hidden="true" class="li_params fs1"></span>
                    </div>
                    <h2>{{ param_text_count }}</h2>
                </div>
            </a>
        </div>

        <!-- DONUT CHART BLOCK -->
        <div class="col-sm-3 col-lg-3">
            <a href="{% url 'principal:list-param-select-admin-view' %}">
                <div class="dash-unit">
                    <h1>PARAM INPUT SELECT</h1>
                    <br>
                    <div class="info-user">
                        <span aria-hidden="true" class="li_params fs1"></span>
                    </div>
                    <h2>{{ param_select_count }}</h2>
                </div>
            </a>
        </div>

        <div class="col-sm-3 col-lg-3">
            <a href="{% url 'principal:list-param-option-admin-view' %}">
                <div class="dash-unit">
                    <h1>PARAM INPUT OPTION</h1>
                    <br>
                    <div class="info-user">
                        <span aria-hidden="true" class="li_params fs1"></span>
                    </div>
                    <h2>{{ param_option_count }}</h2>
                </div>
            </a>
        </div>
    </div><!-- /row -->
</div> <!-- /container -->
<div class="footer-distributed">
    <div class="footer-left">

        <h3>Gene & Genome <span>Annotation For Everybody</span></h3>

        <p class="footer-links">
            <a href="#">Citations</a>
            ·
            <a href="#">Help</a>
            ·
            <a href="#">About</a>
            ·
            <a href="#">Contact</a>
        </p>

        <p class="footer-company-name">CABD &copy; 2018</p>
    </div>

    <div class="footer-center">

        <div>
            <i class="fa fa-map-marker"></i>
            <span style="color:white;">{{ company_name.address }}, Seville, Spain</span>
        </div>

        <div>
            <i class="fa fa-phone"></i>
            <p>{{ company_name.phone }}</p>
        </div>

        <div>
            <i class="fa fa-envelope"></i>
            <p>{{ company_name.email }}</p>
        </div>

    </div>

    <div class="footer-right">

        <p class="footer-company-about">
            <span>About the company</span>
            {{ company_name.description }}
        </p>

        <div class="footer-icons">

            <a href="#"><i class="fa fa-facebook"></i></a>
            <a href="#"><i class="fa fa-twitter"></i></a>
            <a href="#"><i class="fa fa-linkedin"></i></a>
            <a href="#"><i class="fa fa-github"></i></a>

        </div>

    </div>

</div>

</body>
</html>